### PR TITLE
Add a few useful libs by magnars

### PR DESCRIPTION
**Pull request by leifericf**
Add a few useful libraries by @magnars frequently mentioned in Clojurians Slack/#clojure-norway.

### CODE REVIEW

**Comment by weavejester** [comment]
Thanks! Can you change the `test-with-files` key to `test_with_files`?

**Comment by leifericf** [comment]
Fixed naming of `test_with_files` :)

**Comment by leifericf** [comment]
Conflict resolved.

**Comment by weavejester** [comment]
Thanks for fixing the merge conflict as well! But you've changed the `name` rather than the key. Could you swap them around, so that the key has `_` and the name has `-`. This is because the name is what people see, while the key is internal and is limited to `[a-z0-9_]`.

**Comment by leifericf** [comment]
Whops—Sorry about that! Fixed it now.

**Pull request merged**
