### PR TITLE
adding Mulog

### PR DESCRIPTION
**Pull request by BrunoBonacci**
* adding [**µ/log**](https://github.com/BrunoBonacci/mulog) - events logging / structured logging
  * update `safely` added *Circuit Breaker* category

### CODE REVIEW

**Comment by weavejester** [comment]
Please can you remove the 2d06f41 commit from this PR, and remove the "Structured Logging", "Monitoring", "Metering" and "Observability" categories from Mulog.

**Comment by BrunoBonacci** [comment]
Under which category do you want to put libraries for metering like [Dropwizard metrics](https://metrics.dropwizard.io/4.1.2/) and distributed tracing like [Zipkin](https://zipkin.io/)
They all classify broadly under the `Observabilty` tools, but happy to give a more appropriate classification

**Comment by BrunoBonacci** [comment]
Regarding `safely` and the `Circuit Breaker` classification do you want me to push a separate PR?
Or you don't want the Circuit Breaker classification at all?

**Comment by weavejester** [comment]
There's a balance between adding too many categories and too few. In the case of "safely", there's no other project with the "Circuit Breaker" category, so it doesn't really ehlp.

I think for tracing/metrics libraries, maybe add a "Metrics" category.

**Pull request merged**
