### PR TITLE
Add ez-wire for web forms

### PR DESCRIPTION
**Pull request by emil0r**
Added new category Web Forms. ez-wire doesn't really fit into any
other category that I can see.

### CODE REVIEW

**Comment by weavejester** [comment]
What about "HTML Generation"?

**Comment by emil0r** [comment]
ez-wire is meant to be a bigger glue library sitting above reagent and re-frame. Right now it handles forms (definition, validation, rendering, error handling,  etc). Loose future plans include automatic admin interface ala django admin.

So HTML Generation would be a part of what it does, but the library sits a whole layer above pure HTML generation. Throwing out wild ideas here, but is "Web Composition" a better name?

**Comment by weavejester** [comment]
What about "React DOM", then?

**Comment by emil0r** [comment]
Might as well be HTML Generation then, if you wish to keep the number of categories down (understandable). Should I change the category and push again?

**Comment by weavejester** [comment]
I'd like to avoid categories with only one library in, unless the category is obvious. Perhaps "HTML Generation" and "React DOM" categories would work? I believe I'd also accept "DOM Generation", as even though that's a new category, it seems like one that could be filled with other projects as well.

**Comment by emil0r** [comment]
"DOM Manipulation" seems to work better for what the library does. Close enough.

**Pull request merged**
