### PR TITLE
Added Vura to projects.yml

### PR DESCRIPTION
**Pull request by gersak**
Hi, 

I've been working on Clojure/script time computation library and it is ready for it's first release IMO. 

Can this lib join others in Clojure toolbox?

Cheers,
Robert

### CODE REVIEW

**Comment by weavejester** [comment]
Sure. Can you change the category to `[Scheduling]`?

**Comment by weavejester** [comment]
It's not a scheduling lib? In which case, can you change the category to `[Date and Time]`. Please use existing categories where you can, instead of creating new ones.

**Comment by gersak** [comment]
Rats... Sorry about that. I misunderstood. It is both "Date and Time"  and "Scheduling" library but scheduling part isn't documented and tested well. So I've removed Scheduling part...

When the time comes I'll probably open another pull request.

Sorry for unecessary hassle. Is it OK now?

**Comment by weavejester** [comment]
Yep! Merged and deployed.

**Pull request merged**
