### PR TITLE
Add babashka

### PR DESCRIPTION
**Pull request by borkdude**

### CODE REVIEW

**Comment by borkdude** [comment]
@weavejester For fun, I ported clojure-toolbox.com from Ruby to Clojure / babashka: https://github.com/borkdude/clojure-toolbox.com-babashka/commit/5b516fa0e325b7c9ba973a88e4600d3bbad97c66

```
$ time script/generate.clj
Written 763 projects in 214 categories to index.
script/generate.clj   0.21s  user 0.06s system 97% cpu 0.279 total
```

**Comment by weavejester** [comment]
How does that compare to Ruby, out of interest?

**Comment by borkdude** [comment]
@weavejester Ruby was faster: 135ms. I guess there's still work to do ;).

**Comment by borkdude** [comment]
Some performance improvements coming in the next release:

``` clojure
$ bash <(curl https://raw.githubusercontent.com/babashka/babashka/master/install) --version 0.7.5-SNAPSHOT --dir .
$ time ./bb script/generate.clj
Written 763 projects in 214 categories to index.
bb script/generate.clj   0.16s  user 0.05s system 98% cpu 0.213 total
```

**Comment by borkdude** [comment]
Btw, 4 years later, it seems my bb port of the clojure toolbox is now as fast as Ruby:

```
$ time ./script/generate.rb
Written 1017 projects in 237 categories to index.
./script/generate.rb   0,09s  user 0,02s system 94% cpu 0,125 total
```

```
$ time bb generate
Written 1017 projects in 237 categories to index.
bb generate   0,10s  user 0,01s system 97% cpu 0,115 total
```

**Pull request merged**
