### PR TITLE
The happy project has been archived by its author

### PR DESCRIPTION
**Pull request by Rovanion**
I removed it from the list.

My editor also removed some trailing whitespaces.

### CODE REVIEW

**Comment by weavejester** [comment]
Does the author consider the project to be deprecated? That's the obvious assumption, but it would be nice to get confirmation.

**Comment by Rovanion** [comment]
Hi @jeluard, what do you as the author say on the subject?

**Comment by jeluard** [comment]
@Rovanion Yes the project has been archived, it can be removed from the list. Thanks!

**Comment by weavejester** [comment]
Thanks!

**Pull request merged**
